package com.matdev.appcurso.model.entities


import kotlinx.parcelize.Parcelize
import android.os.Parcelable

@Parcelize
data class Meal(
    var dateModified: String? = null,
    var idMeal: String = "",
    var strArea: String = "",
    var strCategory: String = "",
    var strCreativeCommonsConfirmed: String? = null,
    var strDrinkAlternate: String? = null,
    var strImageSource: String? = null,
    var strIngredient1: String = "",
    var strIngredient10: String = "",
    var strIngredient11: String = "",
    var strIngredient12: String = "",
    var strIngredient13: String = "",
    var strIngredient14: String = "",
    var strIngredient15: String = "",
    var strIngredient16: String? = null,
    var strIngredient17: String? = null,
    var strIngredient18: String? = null,
    var strIngredient19: String? = null,
    var strIngredient2: String = "",
    var strIngredient20: String? = null,
    var strIngredient3: String = "",
    var strIngredient4: String = "",
    var strIngredient5: String = "",
    var strIngredient6: String = "",
    var strIngredient7: String = "",
    var strIngredient8: String = "",
    var strIngredient9: String = "",
    var strInstructions: String = "",
    var strMeal: String = "",
    var strMealThumb: String = "",
    var strMeasure1: String = "",
    var strMeasure10: String = "",
    var strMeasure11: String = "",
    var strMeasure12: String = "",
    var strMeasure13: String = "",
    var strMeasure14: String = "",
    var strMeasure15: String = "",
    var strMeasure16: String? = null,
    var strMeasure17: String? = null,
    var strMeasure18: String? = null,
    var strMeasure19: String? = null,
    var strMeasure2: String = "",
    var strMeasure20: String? = null,
    var strMeasure3: String = "",
    var strMeasure4: String = "",
    var strMeasure5: String = "",
    var strMeasure6: String = "",
    var strMeasure7: String = "",
    var strMeasure8: String = "",
    var strMeasure9: String = "",
    var strSource: String? = null,
    var strTags: String = "",
    var strYoutube: String = ""
) : Parcelable